name: .NET Build

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  workflow_dispatch:
    inputs:
      input:
        description: "Bond services to build"
        required: false
        default: "Bond"

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: "5.x"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2
      with:
        useConfigFile: true
        configFilePath: ./GitVersion.yml
 


        
    # - name: Install GitVersion
    #   uses: gittools/actions/gitversion/setup@v0.10.2
    #   with:
    #     versionSpec: "5.x"

    # - name: Checkout code
    #   uses: actions/checkout@v4

    # - name: Determine Version
    #   id: gitversion
    #   uses: gittools/actions/gitversion/execute@v0.10.2
    #   with:
    #     useConfigFile: true
    #     configFilePath: ./GitVersion.yml
 