name: .NET Build

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  workflow_dispatch:
    inputs:
      input:
        description: "Bond services to build"
        required: false
        default: "Bond"

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          8.x
          9.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.2.1
      with:
        versionSpec: '6.0.0'

    - name: Determine Version
      id: version_step # step id used as a reference for output values
      uses: gittools/actions/gitversion/execute@v3.2.1

    - name: Version
      run: |
        echo Building ${{ steps.gitversion.outputs.SemVer }}
         
    - name: Checkout code
      uses: actions/checkout@v4
